[package]
name = "_16_dependencies"
version = "0.1.0"
authors = ["Senthil baliah <Senthil.baliah@zapcg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
